name: Required Labels
on:
  pull_request:
    types: [opened, labeled, unlabeled]
    branches:
      - '!next'
      - '!develop'
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: ejhayes/github-action-required-labels@v1.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: minimum
          count: 1
          labels: 'major,minor,patch,skip-release,internal,documentation,performance'
